### PR TITLE
Fixes compilation on devel and removes most deprecation warnings.

### PR DESCRIPTION
**Pull request by SolitudeSF**

### CODE REVIEW

**Comment by narimiran** [comment]
Nice job @SolitudeSF!

Can this be merged, @ftsf?

**Comment by SolitudeSF** [comment]
yikes, just tried to test if this works and turns out i *somehow* didn't fix correctly `this:self` in examples. gonna fix it sometime soon. **don't think we're in any hurry tho**

**Comment by ftsf** [comment]
Hi, sorry just saw this. I'll look over it and get back to you soon!

I have some local changes that do similar things so I'll compare.

I'm keen to ignore the deprecation of `{.this:self.}` for now until a replacement exists or it's removed entirely as I feel it makes the code a lot more readable.

**Comment by SolitudeSF** [comment]
I would argue that opting for a single letter arg name is a good alternative. And this:self is subjectively confusing.

**Comment by ftsf** [comment]
@SolitudeSF You're right, I've removed use of {.this:self.} in nico and examples, I'll continue to use it in my code that uses nico, but there's no need for its use in the library itself.

I've just pushed my changes that fix compilation on 0.19.4 and removed use of {.this:self.} as well as a bunch of updates and examples.

**Pull request closed without merging**
