### PR TITLE
About to finish cjk font print funcions for nico and these modify test file will close

### PR DESCRIPTION
**Pull request by Angluca**
Screenshot2023-04-23 05 48 27

### CODE REVIEW

**Comment by Angluca** [comment]
https://github.com/kreativekorp/bitsnpicas
ext: *.kbits
This tool can edit fonts  and export  playdata (fnt + png), It's convenient and small, easy

**Comment by Angluca** [comment]
Screenshot2023-04-19 18 29 38

**Comment by Angluca** [comment]
Screenshot2023-04-19 18 32 29

**Review by Angluca — COMMENTED** [review]
- Add run web tips
Newbie don't know how to run web, So add tips

**Comment by Angluca** [comment]
I will finish cjk font print funcions for nico,  Look forward to it!

**Comment by Angluca** [comment]
@matkuki 
It's almost finished.I'll upload it to nico project when it's done, most of the languages are supported
Screenshot2023-04-26 15 05 57

**Comment by matkuki** [comment]
Brilliant 🎉

**Pull request closed without merging**
